### ISSUE TITLE
SPM Build Tool Plugin excessively runs causing recompilation

### ISSUE THREAD

**Issue by Brett-Best** [swiftlang/swift-package-manager#8273]
I use https://github.com/liamnichols/xcstrings-tool, this essentially takes in inputs of `*.xcstring` and outputs `*.swift`.
Unfortunately, this is having a large impact on incremental builds where for some reason the build tool plugin runs every time.
This invalidates already compiled SPM targets leading to a large incremental compile time of >100 seconds in a project I work on.

This issue can be reproduced using https://github.com/liamnichols/xcstrings-tool-demo.

I also notice that the `CompileXCStrings` job runs on every incremental build as well.

I've tested this using Xcode 16.2 and using Xcode 16.2 with latest main of this repository.

CC: @dschaefer2

[Build DogTracker_2025-02-03T05-22-22.txt](https://github.com/user-attachments/files/18633394/Build.DogTracker_2025-02-03T05-22-22.txt)
[Build DogTracker_2025-02-03T05-22-36.txt](https://github.com/user-attachments/files/18633395/Build.DogTracker_2025-02-03T05-22-36.txt)

**Comment by dschaefer2** [comment]
We'll start investigating this with the swift-package-manager.

**Comment by bcardarella** [comment]
Is there any update on this yet? We've seen re-build times go from seconds to well over 20 minutes due to what we suspect is this issue.

**Comment by dschaefer2** [comment]
The example project is an Xcode project. We only deal with command line SwiftPM issues on GitHub. Can you reproduce this issue with a SwiftPM package?

**Comment by tonyarnold** [comment]
Here's a sample showing the same behaviour in a Swift Package. Run `swift build` more than once, and you'll see the build plugin run every time, regardless of changes to the inputs: 

```
❯ swift build
[1/1] Planning build
Building for debugging...
/Users/tonyarnold/Desktop/ExcessiveBuildToolCompilation/Sources/ExcessiveBuildToolCompilation/Resources/Localizable.xcstrings: warning: String ‘Function Grapher‘ was ignored because it does not have a translation for source language (en)
/Users/tonyarnold/Desktop/ExcessiveBuildToolCompilation/Sources/ExcessiveBuildToolCompilation/Resources/Localizable.xcstrings: warning: String ‘Please enter valid range values‘ was ignored because it does not have a translation for source language (en)
/Users/tonyarnold/Desktop/ExcessiveBuildToolCompilation/Sources/ExcessiveBuildToolCompilation/Resources/Localizable.xcstrings: warning: String ‘Range‘ was ignored because it does not have a translation for source language (en)
note: Output written to ‘/Users/tonyarnold/Desktop/ExcessiveBuildToolCompilation/.build/plugins/outputs/excessivebuildtoolcompilation/ExcessiveBuildToolCompilation/destination/XCStringsToolPlugin/XCStringsTool/Localizable.swift‘
/Users/tonyarnold/Desktop/ExcessiveBuildToolCompilation/.build/plugins/outputs/excessivebuildtoolcompilation/ExcessiveBuildToolCompilation/destination/XCStringsToolPlugin/XCStringsTool/Localizable.swift:108:14: error: type 'Bundle' has no member 'module'
106 |         var bundle: Bundle {
107 |             #if SWIFT_PACKAGE
108 |             .module
    |              `- error: type 'Bundle' has no member 'module'
109 |             #else
110 |             Bundle(for: BundleLocator.self)
[16/16] Compiling ExcessiveBuildToolCompilation Localizable.swift
```

[ExcessiveBuildToolCompilation.zip](https://github.com/user-attachments/files/19153263/ExcessiveBuildToolCompilation.zip)

**Comment by tonyarnold** [comment]
@dschaefer2 are you certain that this is an issue with SwiftPM, rather than Swift Build? It seems to affect both Xcode _and_ SwiftPM.

**Comment by bcardarella** [comment]
fwiw we're seeing our issue fixed in the latest xcode betas

**Comment by Brett-Best** [comment]
Yeah, with the latest Xcode betas I was unable to create a reproducer that `swift build` could show.
It's still an issue with Xcode 16.3b2 including using latest main of `swift-build`.

I'm wondering if @dschaefer2 could direct where this issue would be best moved to based on that, back to `swift-build`?

**Comment by owenv** [comment]
I'm going to pull this over to Swift Build as it looks like potentially an issue with incremental invalidation in the build engine and the issue is primarily describing package builds driven via Xcode.
